### ISSUE TITLE
LaTeX Error: File `droidmono.sty' not found.

### ISSUE THREAD

**Issue by beune** [randombenj/modern-latex-theme#3]
Compiled the following document with the command and parameters from the README:
`\documentclass{modern}`
`\begin{document}`
    `FOO`
`\end{document}`

Results in the following error:
`LaTeX Error: File droidmono.sty not found.`

I am running Arch Linux with the `texlive-most` package group.

`droidmono` seems like a font. Do I need to install this?

**Comment by randombenj** [comment]
Yes on ubuntu you need to install the `texlive-fonts-extra` package, is there something similar in arch?
It exists in bionic: https://packages.ubuntu.com/search?suite=bionic&arch=any&mode=exactfilename&searchon=contents&keywords=droidmono.sty but it doesn't seem to be there in focal anymore. Maybe I need to change to another font then ...

**Comment by beune** [comment]
It appears I already have the `texlive-fontsextra` package installed. I guess this is not the problem then.

**Comment by randombenj** [comment]
Hmm then they probably removed this font in the later versions ... As a workaround you can just remove this line: https://github.com/randombenj/modern-latex-theme/blob/master/modern.cls#L105 and this one: https://github.com/randombenj/modern-latex-theme/blob/master/modern.cls#L110

I will probably switch to another monospace font then ...
Thanks for the issue :beers:

**Comment by beune** [comment]
As the `/usr/local/share/texmf/tex/latex/` folder does not exist on my system, I copied the `modern.cls` with the changes to both `/usr/share/texmf-dist/tex/luatex` and `/usr/share/texmf-dist/tex/latex`. I `chown`'ed the file to my user, and ran `sudo mktexlsr`. 

Now I get the following error when compiling with `luatex`:
`! Package minted Error: You must have 'pygmentize' installed to use this packag
e.`

See my log file for more info.
[foo.log](https://github.com/randombenj/modern-latex-theme/files/5223368/foo.log)

**Comment by randombenj** [comment]
This might be because `python-pygments` is missing on your system?

**Comment by beune** [comment]
Alright, now the workaround fixed the problem. Thanks! Should I leave this issue opened?

**Comment by randombenj** [comment]
Yes, thanks for the feedback, I will probably search for a more common monospace font and close it then :)
